[package]
name = "zrtp-proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nom.workspace = true
byteorder.workspace = true
crc.workspace = true
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
